### ISSUE TITLE
Error when exporting orders

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.shop#43]
I tried to export some orders and just filled up the "to date" inputbox and pressed "export". It showed up  the error:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bda.plone.orders.browser.views, line 1035, in **call**
  Module yafowil.controller, line 18, in **init**
  Module yafowil.base, line 380, in extract
    yafowil widget processing info:
    - path      : exportorders
    - blueprints: ['form']
    - task      : extract
    - descr     : failed at 'form'
  Module yafowil.compound, line 26, in compound_extractor
  Module yafowil.compound, line 31, in compound_extractor
  Module yafowil.base, line 380, in extract
    yafowil widget processing info:
    - path      : exportorders.to
    - blueprints: ['td', 'field', 'plonelabel', 'error', '*from_before_to', 'datetime']
    - task      : extract
    - descr     : failed at 'from_before_to'
  Module bda.plone.orders.browser.views, line 1056, in from_before_to
TypeError: can't compare datetime.datetime to str

**Comment by jensens** [comment]
compare now moved here, no idea why there is a string at your place. 
https://github.com/bluedynamics/bda.plone.orders/blob/master/src/bda/plone/orders/browser/export.py#L163

**Comment by rnixx** [comment]
just tested order export yesterday. this problem seems to be gone in the meantime.
