### ISSUE TITLE
Shop settings can't be saved - available shippings missing

### ISSUE THREAD

**Issue by frisi** [bluedynamics/bda.plone.shop#55]
Changes in Plone/@@shop_controlpanel can't be saved because the widget for shipping and payment methods seems to be broken.

The vocabularies  (`AvailableShippingMethodsVocabulary` and `ShippingMethodsVocabulary`) both work fine, but the widget for `IShopShippingSettings.available_shipping_methods` seems to be broken.
It does not display any selectable items.

![shipping](https://cloud.githubusercontent.com/assets/1120517/8306665/07d96c70-19ba-11e5-9375-3b30d21a4750.png)

Running Plone 4.3.6

**Comment by frisi** [comment]
@rnixx looks like a bug somewhere in the plone stack or a wrong version of some package. do you have any hint?

**Comment by rnixx** [comment]
have you tried in a vanilla plone?

**Comment by frisi** [comment]
yep - the same.

**Comment by frisi** [comment]
looks like this is related to the problem with the tax settings not showing up: https://github.com/bluedynamics/bda.plone.shop/commit/30a5fa27b4bcb934ea0ab80944e6389100eb26b0#commitcomment-11814716

according to interfaces.IShopTaxSettings.vat the `z3c.form.browser.checkbox.CheckBoxFieldWidget` is used.
z3c.form version 3.2.3

**Comment by rnixx** [comment]
please try debugging the vocabularies used in the corresponding widgets at first whether they return useful stuff.

there exists an available and an enabled vocab for some values just to keep in mind.

**Comment by frisi** [comment]
i already tried out both vocabularies:

> The vocabularies (AvailableShippingMethodsVocabulary and ShippingMethodsVocabulary) both work fine, but the widget for IShopShippingSettings.available_shipping_methods seems to be broken.

i even tried to use the ShippingMethodsVocabulary (which is used for default-shipping - this one can be selected in the screenshot) for the available_shipping_methods field.
field also empty. 
do the values show up on your installation? i think this is some z3c.form or plone.app.registry problem (see my comment above)

**Comment by rnixx** [comment]
i have no time right now investigating the problem. i'll fire up my development instance later and check whether this error happens

**Comment by frisi** [comment]
@agitator do you have the same problem on your shop instance (when updating to current master of all shop packages)?

**Comment by agitator** [comment]
using an earlier release within my client projects, no need to update for me right now ;-)
