### ISSUE TITLE
Allow shop admin portlet entries to be easily included in header bar

### ISSUE THREAD

**Issue by thet** [bluedynamics/bda.plone.shop#68]
The shop admin portlet entries should be allowed to provided in a header bar as dropdown.
I see following options:
- Moving the portlet's contents via Diazo into a reserved space in the theme (ugly)
- Using a viewlet manager to provide the entries (better)
- Reimplementing it as portal_action entries (maybe best?)

**Comment by frisi** [comment]
just stumbled over https://github.com/collective/collective.portlet.actions which might help to allow users to stay with the portlet after actions have been migrated to portal_actions

**Comment by rnixx** [comment]
I moved the logic for creating shop navigation links to ``bda.plone.shop.browser.navigation``.

Further there exists now an integration to Plone 5 toolbar here https://github.com/bluedynamics/bda.plone.shop/blob/master/src/bda/plone/shop/browser/toolbar.py and here https://github.com/bluedynamics/bda.plone.shop/blob/master/src/bda/plone/shop/browser/configure.zcml#L180

Also the shop admin portlet gets no assignment on install in Plone 5 any more.

I don't know how integration to content views needs to be implemented in Plone 4, if someone still needs this the navigation and toolbar implementations are good places to start.
