### ISSUE TITLE
Allow admins to cancel and reorder bookings

### ISSUE THREAD

**Issue by thet** [bluedynamics/bda.plone.shop#76]
A shop admin should be able to cancel a booking on request of the customer and reorder it in their name. The process is like following:

1) Admin cancels a individual booking or order.
2) A notification email regarding the cancellation is sent to customer and admin. (available items have to be increased again with the number of canceled items)
3) Admin reorders a item in the name of the customer.
4) A notification email regarding the order is sent to customer and admin.

This was part of https://github.com/bluedynamics/bda.plone.shop/issues/69 but now in it's own ticket.

Not sure, if a whole order should be canceled instead of an individual booking.

Any comments?

/cc @rnixx @pcdummy @frisi

**Comment by frisi** [comment]
from an end-user point of view the shop should support both:
* cancel bookings in an order and
* cancelling a complete order (all contained bookings)

just to be sure: it should be possible to cancel multiple bookings with a single post to the server, so only one email is sent to the customer (cancelling 3 bookings == 3 emails would not be the best solution i think)

what do you mean with "reorder"? change quantity to more?
so cancel would mean change quantity to less or 0

should it also be possible to add completely new bookings (add new items out of the shop) to the order? or is this out of scope here

**Comment by rnixx** [comment]
Editing orders should be implemented in order details view, where recently the comment of a booking can be edited and a single booking can be cancelled.

A check box should be added for each booking and the cancel action should be made "global", like the mail notification action for orders in orders overview works (I agree with @frisi that notification should only be sent once for a multi-booking-cancel action.)

Cancelling a complete order already works in orders overview (not sure whether a cancellation email is sent, though. This needs to be checked).

Adding new bookings is more tricky. It should also be an action in order details, maybe something like "add items in cart to order". This would make selecting items to add the same as regular shopping. But this also implies that availability checks can not be bypassed.

Adding complete orders on behalf of a customer is a different story and requires another UI. We already implemented such a functionality some years ago for a customer in a proprietary solution. It worked the way that the back-office staff collected the requested items in cart, supported by a list of bookmarks which provided a short-cut for adding frequently ordered items to cart. Then a simplified checkout was provided. We would further need a step in between selecting a contact from our stored contacts list.

**Comment by rnixx** [comment]
![order](https://cloud.githubusercontent.com/assets/246021/15359472/d3e7ea0a-1d09-11e6-89dd-e3f213a7e04f.png)

**Comment by rnixx** [comment]
![orders](https://cloud.githubusercontent.com/assets/246021/15359519/fc60c434-1d09-11e6-8451-3a96a9628e3f.png)

**Comment by thet** [comment]
Stale issue.
