### ISSUE TITLE
ICartItemStock should not be required for an item to be buyable

### ISSUE THREAD

**Issue by agitator** [bluedynamics/bda.plone.shop#77]
The buyable viewlet produces an error if ICartItemStock is not provided by the item that's buyable.

`TypeError: ('Could not adapt', <File at /Plone/buyable_document_d.pdf>, <InterfaceClass bda.plone.cart.interfaces.ICartItemStock>)
`

**Comment by rnixx** [comment]
This should already be fixed. May you check please?
