### ISSUE TITLE
Merge plone5 branches back to master

### ISSUE THREAD

**Issue by rnixx** [bluedynamics/bda.plone.shop#80]
TODO:

- [ ] https://github.com/plone/Products.CMFPlone/issues/1529
- [x] Finish YAFOWIL plone 5 port
- [x] Cart Base URL Handling
- [x] Fix datagridfield in plone 5

**Comment by ezvirtual** [comment]
Hey BDA team,
We were wondering if you could provide any insight as to the current state of bda.plone.shop with Plone 5?

Can you share any plans / time-lines that you have around the above task list being carried out and b.p.shop being P5 compatible / merged back into master? 

Are there any tasks on the list that you would suggest could be easily looked at by people who don't have the in-depth knowledge of b.p.shop / yafowil that you do? If so, perhaps you could provide a small outline of where to start looking at these?

Thank you all very much for all of the collective effort that has gone in to this add-on! It's certainly not my intention to come across demanding, I'm just hoping to gain an idea of what you are planning. :)

**Comment by rnixx** [comment]
Hi,

Currently the resource registry issue linked above is the last known unknown to become reliably plone 5 ready.

The plone 5 branches are compatible with plone 4, we register different resources and GS profiles for each version. So actually merging back to master would be possible right now.

Yafowil is also plone 5 ready so far, we migrated it while improving pas.plugins.ldap and node.ext.ldap. Some yafowil addon widgets needs some style and JS love though, but afaik none of them are used in the shop stack.

Cart base URL handling was implemented by @agitator yesterday.

Datagridfield in plone 5 needs another test, maybe it simply works in the meantime.

So what's missing:
- Merge https://github.com/bluedynamics/bda.plone.orders/pull/39 (I'll review ASAP)
- Test install and basic usage on p4 and p5 (everyone is welcome to help and test)
- Merge branches
- Finally release packages on pypi

Referring a concrete timeline - all current shop projects out there (in my sphere of action) are p4, all the p5 work until now has been done foresightful. So all I can say now is that it's done when it's done.

Any help is appreciated.

**Comment by agitator** [comment]
two Plone 5 shop projects here that should be finished by end of august and end of september 

mostly polishing that's missing from my pov (so far)

**Comment by ezvirtual** [comment]
You guys are legends! Will see what we can do :)

**Comment by agitator** [comment]
Help is always welcome ;-)

**Comment by rnixx** [comment]
Plone 5 basically works now. Even if plone/Products.CMFPlone#1529 is still not solved properly, I have merged back the plone5 branches to master. Please test and report bugs and inconsistencies.
