### ISSUE TITLE
Downloadable/virtual Items?

### ISSUE THREAD

**Issue by TBCcrash2064** [bluedynamics/bda.plone.shop#98]
Hi,
is it possible to create virtual Items to download like music-files or pdfs with bda.plone.shop?

**Comment by agitator** [comment]
Sure, there is a flag in the control panel to disable shipping calculation
https://github.com/bluedynamics/bda.plone.shop/blob/master/src/bda/plone/shop/profiles/base/registry.xml#L39

You have to implement a lock/unlock mechanism for your digital items and usecase yourself though.
